### ISSUE TITLE
Task - Dummy Portal Screen

### ISSUE THREAD

**Issue by akshitg3** [Spitgranger/SyncMaster#251]
**Description**
Create a screen showing the message "Contractor Portal"
Add some dummy fields like: work order number, name and email

Extra:
* Add css styling to make the page look nicer

**Definition of Done**
A functional satisfying the above requirements

**Comment by MitchHynes** [comment]
- Installed NodeJS and expressJS on my computer (Nov 11)
- Watching this tutorial to learn what ExpressJS is: https://www.youtube.com/watch?v=SccSCuHhOw0
- Created a new project on my computer to play around with the features from that tutorial. Currently trying to create a page in that temporary app to learn how it is done, then use the same process for this issue.

**Comment by MitchHynes** [comment]
Our project is different from that tutorial, we are using typescript whereas the tutorial did not. But in general what I learned seems to apply. Need to figure out why the res.render on the views/portal.ejs wasn't resolving the path.

**Comment by MitchHynes** [comment]
2024/11/11 - Above tutorial that I followed developed the application from server side, feedback with team is that we won't take that approach. I will find and follow a different tutorial which develops the dummy portal screen inside of a "nextJS environment".
Rafeed provided this documentation: https://nextjs.org/docs/app/getting-started/project-structure
I will also watch this youtube video: https://www.youtube.com/watch?v=TJQbDPGzm0Y

**Comment by MitchHynes** [comment]
Edit, I will not watch the above youtube video. It is using react as a frontend framework (in addition to nextJS)? We are not using React for this milestone.

**Comment by MitchHynes** [comment]
Learned the following helpful information from Akshit:
![image](https://github.com/user-attachments/assets/74d3060c-1df7-45af-87be-b0792deaca5a)

React and nextjs can be used together, nextjs being the frontend framework and react the library to build the interfaces. I will revit the above tutorial
